# Generated by Django 3.2.3 on 2021-06-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_cctv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CctvDTO',
            new_name='CrimeVo',
        ),
    ]
